### ISSUE TITLE
render throws exception

### ISSUE THREAD

**Issue by hdenk** [noir-clojure/noir#22]
render doesn't work any more for me. syntax-change or error ?

cause may be commit 930544302a496297cdd8

i am using 1.1.1-SNAPSHOT.

my code:

(noir/defpage [:post "/orders/new"] {:as order}
    (if (and (valid-order? order) (model/add-order! order))
      (response/redirect "/orders")
      (noir/render "/orders/new" order)))

the Stacktrace:

java.lang.Exception: Routes must either be a string or vector, not a class java.lang.Character
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
    at clojure.lang.Reflector.invokeConstructor(Reflector.java:183)
    at noir.core$throwf.doInvoke(core.clj:26)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at noir.core$parse_route.invoke(core.clj:36)
    at noir.core$parse_args.invoke(core.clj:59)

**Comment by ibdknox** [comment]
apologies! This was something that didn't get verified with named routes. I've fixed this and added a test to make sure it doesn't happen again. Latest push to clojars should have what you need. :)

Depending on when you last did lein deps, you may need to remove ~/.m2/repository/noir/ folder to get it to check for it again.
