### ISSUE TITLE
Static files with space characters aren't routed properly

### ISSUE THREAD

**Issue by kzar** [noir-clojure/noir#36]
I've noticed that static files containing spaces aren't routed properly. 

The space is replaced by %20 because the URL is encoded. Problem is that the file name is not decoded again, so the file wont exist.

For example if I have an image `/resources/public/images/example image.png`, I would add the tag `<img src="/images/example image.png" />` and then an exception would be thrown because `/resources/public/images/example%20image.png` doesn't exist.

Cheers, Dave.

**Comment by ghost** [comment]
This also is a problem when using Noir on Windows below the 'Documents and Settings' directory. If a typical user creates a project directory in their home account they won't be able to serve static files in development.

**Comment by gberenfield** [comment]
+1 seeing this too. Seems like a URLDecoder/decode call needs to happen. Should be in wrap-url-decode I think...

**Comment by kzar** [comment]
Well I had another look at this and I noticed a few things:
1. wrap-url-decode already does use URLDecoder/decode to decode the filename and path properly.
2. Looking at the logic wrap-url-decode is called before the compojure.route/resources route is used.
3. At some point afterwards the request :uri is encoded again, causing the request to fail.
4. Note that the 404 route is not hit when the file name should be valid if it weren't for the encoding problem, instead an exception is thrown. So for example "/valid file.png" would throw an exception but "/invalid file.png" would give a 404!

The exception:

```
  java.io.FileNotFoundException: /Users/kzar/Desktop/clojure/noir/resources/public/test%20example.jpeg (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:120)
    at ring.util.servlet$set_body.invoke(servlet.clj:96)
    at ring.util.servlet$update_servlet_response.invoke(servlet.clj:124)
    at ring.adapter.jetty$proxy_handler$fn__2574.invoke(jetty.clj:18)
    at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown Source)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by gberenfield** [comment]
[This is a ring issue, through compojure.](https://github.com/weavejester/compojure/issues/46) Compojure 1.0.0-RC2 has the fix

**Comment by ibdknox** [comment]
Moved to 1.0.1 of ring, so this should be fixed.
